NDefines.NGame.GAME_SPEED_SECONDS = { 600.0, 0.5, 0.2, 0.1, 0.0 }
NDefines.NGame.COMBAT_LOG_MAX_MONTHS = 36

NDefines.NDiplomacy.BASE_SEND_ATTACHE_COST = 150
NDefines.NDiplomacy.BASE_SEND_ATTACHE_CP_COST = 0

NDefines.NCountry.REINFORCEMENT_MANPOWER_DELIVERY_SPEED = 50.0 --316
NDefines.NCountry.BASE_MAX_COMMAND_POWER = 100.0 -- 442
NDefines.NCountry.AIR_VOLUNTEER_PLANES_RATIO = 0 --444
NDefines.NCountry.AIR_VOLUNTEER_BASES_CAPACITY_LIMIT = 0 -- 445
NDefines.NCountry.SPECIAL_FORCES_CAP_BASE = 0 -- 447
NDefines.NCountry.SPECIAL_FORCES_CAP_MIN = 10000 -- 448

NDefines.NProduction.DEFAULT_MAX_NAV_FACTORIES_PER_LINE = 50
NDefines.NProduction.CONVOY_MAX_NAV_FACTORIES_PER_LINE = 50
NDefines.NProduction.CAPITAL_SHIP_MAX_NAV_FACTORIES_PER_LINE = 50
NDefines.NProduction.RAILWAY_GUN_MAX_MIL_FACTORIES_PER_LINE = 10
NDefines.NProduction.BASE_COUNTRY_ENERGY_PRODUCTION = 0
NDefines.NProduction.ENERGY_COST_CAP = 0
NDefines.NProduction.BASE_FACTORY_SPEED = 5
NDefines.NProduction.BASE_FACTORY_SPEED_MIL = 4.5
NDefines.NProduction.BASE_FACTORY_SPEED_NAV = 2.5
NDefines.NProduction.BASE_FACTORY_MAX_EFFICIENCY_FACTOR = 40
NDefines.NProduction.MIN_POSSIBLE_TRAINING_MANPOWER = 10000000
NDefines.NProduction.MIN_FIELD_TO_TRAINING_MANPOWER_RATIO = 100.0
NDefines.NProduction.BASE_LICENSE_IC_COST = 0
NDefines.NProduction.LICENSE_IC_COST_YEAR_INCREASE = 0
NDefines.NProduction.LICENSE_EQUIPMENT_TECH_SPEED_PER_YEAR = 0
NDefines.NProduction.LICENSE_EQUIPMENT_UPGRADE_XP_FACTOR = 0
NDefines.NProduction.EQUIPMENT_MODULE_ADD_XP_COST = 0
NDefines.NProduction.EQUIPMENT_MODULE_REPLACE_XP_COST = 0
NDefines.NProduction.EQUIPMENT_MODULE_CONVERT_XP_COST = 0
NDefines.NProduction.EQUIPMENT_MODULE_REMOVE_XP_COST = 0
NDefines.NProduction.MINIMUM_NUMBER_OF_FACTORIES_TAKEN_BY_CONSUMER_GOODS_VALUE = 0
NDefines.NProduction.MINIMUM_NUMBER_OF_FACTORIES_TAKEN_BY_CONSUMER_GOODS_PERCENT = 0

NDefines.NBuildings.MAX_SHARED_SLOTS = 100
NDefines.NBuildings.INFRASTRUCTURE_RESOURCE_BONUS = 0.075

NDefines.NMilitary.MAX_LEADERS_TO_SHOW = 0
NDefines.NMilitary.MIN_DIVISION_BRIGADE_HEIGHT = 5
NDefines.NMilitary.BASE_DIVISION_BRIGADE_GROUP_COST = 0
NDefines.NMilitary.BASE_DIVISION_BRIGADE_CHANGE_COST = 0
NDefines.NMilitary.BASE_DIVISION_SUPPORT_SLOT_COST = 0
NDefines.NMilitary.TRAINING_EXPERIENCE_SCALE = 0
NDefines.NMilitary.EXPERIENCE_COMBAT_FACTOR = 0.05
NDefines.NMilitary.TRAINING_ATTRITION = 0
NDefines.NMilitary.BATALION_CHANGED_EXPERIENCE_DROP = 0
NDefines.NMilitary.LAND_EQUIPMENT_BASE_COST = 0
NDefines.NMilitary.LAND_EQUIPMENT_RAMP_COST = 0
NDefines.NMilitary.NAVAL_EQUIPMENT_BASE_COST = 0
NDefines.NMilitary.NAVAL_EQUIPMENT_RAMP_COST = 0
NDefines.NMilitary.AIR_EQUIPMENT_BASE_COST = 0
NDefines.NMilitary.AIR_EQUIPMENT_RAMP_COST = 0
NDefines.NMilitary.AIR_WING_COUNTRY_XP_FROM_TRAINING_FACTOR = 0
NDefines.NMilitary.AIR_WING_XP_TRAINING_MISSION_ACCIDENT_FACTOR = 0

NDefines.NAir.AIR_WING_FLIGHT_SPEED_MULT = 0.1
NDefines.NAir.COMBAT_DAMAGE_SCALE = 0.5
NDefines.NAir.AIR_DEPLOYMENT_DAYS = 0
NDefines.NAir.DISRUPTION_FACTOR = 2.5

NDefines.NNavy.TRAINING_ACCIDENT_CHANCES = 0

NDefines.NDoctrines.TRAINING_MASTERY_GAIN_FACTOR = 0